version: '3.2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  builder-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3005"
    environment:
      - INSTANCE=builder-server
  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - builder-server
    ports:
      - "8080:80"
    links:
      - builder-server:builder-server
    restart: always